ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o