ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7
ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
