ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o