ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranovexx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranovexx/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranovexx/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
