ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7lte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7lte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7lte/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
