ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
