# Makefile for Vibrator controlled by PMIC Regulator.
obj-$(CONFIG_MSM_VIBRATOR) += msm_vibrator.o
obj-$(CONFIG_BLDC_VIBRATOR) += bldc_vibrator.o

obj-$(CONFIG_SS_VIBRATOR) += ss_vibrator.o

# Makefile for Vibrator controlled by SUB PMIC Regulator.
obj-$(CONFIG_SM5703_VIBRATOR) += sm5703_vibrator.o


