ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
