ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7
ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
