ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5x
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5x/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5x/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
