ccflags-y += -Idrivers/media/platform/msm/camera_v2_j3x
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j3x/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j3x/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
