ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranovexx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranovexx/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranovexx/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
