#
# panel object
# namd : samsung_dsi_panel_"DDI VENDOR"_"DDI NAME"_"PANEL VENDOR"_"PANEL NAME".c
#
obj-y  += ss_dsi_panel_EA8061V_AMS497EE01.o

#
# smart dimming function
#
obj-y  += ss_dsi_smart_dimming_EA8061V_AMS497EE01.o
