ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
