ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
