ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o