ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7
ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_o7/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o
