ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_i2c_mux.o msm_camera_spi.o msm_camera_dt_util.o
