ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o
