obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_platform.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_core.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_device_access.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_i2c.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_loader.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_mt_common.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_samsung_factory.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5_DEVICETREE_SUPPORT) += cyttsp5_devtree.o

# CFLAGS_cyttsp5_core.o += -DDEBUG
# CFLAGS_cyttsp5_i2c.o += -DDEBUG
# CFLAGS_cyttsp5_mtb.o += -DDEBUG
# CFLAGS_cyttsp5_mt_common.o += -DDEBUG
# CFLAGS_cyttsp5_device_access.o += -DDEBUG
# CFLAGS_cyttsp5_loader.o += -DDEBUG $(CYTTSP_CFLAGS)
# CFLAGS_cyttsp5_platform.o += -DDEBUG $(CYTTSP_CFLAGS)
# CFLAGS_cyttsp5_samsung_factory.o += -DDEBUG
