ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranoveltexx/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
