ccflags-y += -Idrivers/media/platform/msm/camera_v2_gt5
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gt5/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gt5/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
