ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_fortuna/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
