ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5x
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5x/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j5x/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
