ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7lte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7lte/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7lte/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
