ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_gte/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
